id: P005449
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W8LS17154
  title: སྤྱོད་འཇུག་ཚིག་འགྲེལ་འཇམ་དབྱངས་བླ་མའི་ཞལ་ལུང་བདུད་རྩིའི་ཐིག་པ།
  author: ''
  volumes:
    8a7c994fc0724fca8e187e791afb9931:
      image_group_id: I8LS17162
      title: ''
      volume_number: 1
      total_pages: 756
      base_file: v001.txt
