id: P005449
initial_creation_type: ocr
source_metadata:
  id: bdr:W8LS17154
  title: སྤྱོད་འཇུག་ཚིག་འགྲེལ་འཇམ་དབྱངས་བླ་མའི་ཞལ་ལུང་བདུད་རྩིའི་ཐིག་པ།
  author: ''
  volumes:
    8a7c994fc0724fca8e187e791afb9931:
      image_group_id: I8LS17162
      title: ''
      volume_number: 1
      total_pages: 756
